Added temp path creation if doesn't exist
kodus/tempkit pull request #1
Opened 2017-05-04 12:48 UTC by visiover

2017-05-04 13:43 UTC, mindplay-dk requested changes
a simple `mkdir()` and `chmod()` will do - we don't need a function for recursive directory creation, since that's not allowed in the first place.

2017-05-04 14:18 UTC, rhl-jfm approved these changes

2017-05-05 06:20 UTC, boan-jfm approved these changes

2017-05-06 07:53 UTC, mindplay-dk approved these changes
Looks good, thanks man :-)

2017-05-06 07:53 UTC, merged